config/routes.rb
Rails.application.routes.draw do
  resources :vdos
  resources :videos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vdo.rb
class Vdo < ApplicationRecord
end

app/models/video.rb
class Video < ApplicationRecord
	 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vdos_controller.rb
class VdosController < ApplicationController
  before_action :set_vdo, only: [:show, :edit, :update, :destroy]

  # GET /vdos
  # GET /vdos.json
  def index
    @vdos = Vdo.all
  end

  # GET /vdos/1
  # GET /vdos/1.json
  def show
  end

  # GET /vdos/new
  def new
    @vdo = Vdo.new
  end

  # GET /vdos/1/edit
  def edit
  end

  # POST /vdos
  # POST /vdos.json
  def create
    @vdo = Vdo.new(vdo_params)

    respond_to do |format|
      if @vdo.save
        format.html { redirect_to @vdo, notice: 'Vdo was successfully created.' }
        format.json { render :show, status: :created, location: @vdo }
      else
        format.html { render :new }
        format.json { render json: @vdo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vdos/1
  # PATCH/PUT /vdos/1.json
  def update
    respond_to do |format|
      if @vdo.update(vdo_params)
        format.html { redirect_to @vdo, notice: 'Vdo was successfully updated.' }
        format.json { render :show, status: :ok, location: @vdo }
      else
        format.html { render :edit }
        format.json { render json: @vdo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vdos/1
  # DELETE /vdos/1.json
  def destroy
    @vdo.destroy
    respond_to do |format|
      format.html { redirect_to vdos_url, notice: 'Vdo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vdo
      @vdo = Vdo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vdo_params
      params.require(:vdo).permit(:title, :body)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
    require 'video_info'


  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new

    @video = Video.new

  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vdos_helper.rb
module VdosHelper
end

app/helpers/videos_helper.rb
module VideosHelper

	def youtube_id
    	YouTubeAddy.extract_video_id(@video.title)
  	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Utest2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vdos/_form.html.erb
<%= form_with(model: vdo, local: true) do |form| %>
  <% if vdo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vdo.errors.count, "error") %> prohibited this vdo from being saved:</h2>

      <ul>
      <% vdo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vdos/edit.html.erb
<h1>Editing Vdo</h1>

<%= render 'form', vdo: @vdo %>

<%= link_to 'Show', @vdo %> |
<%= link_to 'Back', vdos_path %>

app/views/vdos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vdos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vdos.each do |vdo| %>
      <tr>
        <td><%= vdo.title %></td>
        <td><%= vdo.body %></td>
        <td><%= link_to 'Show', vdo %></td>
        <td><%= link_to 'Edit', edit_vdo_path(vdo) %></td>
        <td><%= link_to 'Destroy', vdo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vdo', new_vdo_path %>

app/views/vdos/new.html.erb
<h1>New Vdo</h1>

<%= render 'form', vdo: @vdo %>

<%= link_to 'Back', vdos_path %>

app/views/vdos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @vdo.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @vdo.body %>
</p>

<%= link_to 'Edit', edit_vdo_path(@vdo) %> |
<%= link_to 'Back', vdos_path %>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>


<div class="embed-responsive embed-responsive-16by9">
	<iframe class="embed-responsive-item" src='https://www.youtube.com/embed/<%= youtube_id%>'allowfullscreen></iframe>
</div>



<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>